1 start
EgorLepskii/react-project pull request #1
Opened 2023-08-23 08:54 UTC by EgorLepskii

Может потребоваться ввести npm i --force, тк присутствует конфликт с stylelint-order-config-standard

2023-08-27 10:37 UTC, Grinv requested changes

2023-08-27 10:37 UTC, Grinv commented on app/components/Button/Button.tsx
> +        })}><Arrow/></label>}
Давай будем писать структурно и чтоб было читать легче. Тут всё вмешалось в одной строке. родители, пропсы, чилдрены, классы.
```jsx
<button
  className={cn(styles.button, className, {
    [styles.primary]: appear === 'primary',
    [styles.ghost]: appear === 'ghost',
  })}
  {...props}
>
  {children}
  {direction !== 'none' && (
    <label
      className={cn(styles.arrow, {
        [styles.right]: direction === 'right',
        [styles.down]: direction === 'down',
      })}
    >
      <Arrow />
    </label>
  )}
</button>
```
вот так гораздо понятнее

2023-08-27 10:37 UTC, Grinv commented on app/components/Button/Button.tsx
> +        <button className={cn(styles.button, className, {
Чтоб немного облегчить чтение, можно классы объявить заранее
```jsx
const buttonClasses = cn(styles.button, className, {
   [styles.primary]: appear === 'primary',
   [styles.ghost]: appear === 'ghost'
});

return <button {...props} className={buttonClasses}>

2023-08-27 10:37 UTC, Grinv commented on app/components/Button/Button.tsx
> +        })} {...props}>{children}{direction !== 'none' && <label className={cn(styles.arrow, {
Спрэды лучше объявлять первыми, ибо это чёрный ящик, наполнение которого мы не всегда контроллируем. Поэтому можно случайно переписать пропсы, которые объявивили до этого и будет тяжело деббажить.
```jsx
<button {...props} className={className}>

2023-08-27 10:37 UTC, Grinv commented on app/components/Button/Button.tsx
> +        })}><Arrow/></label>}
Я бы советовал всё-таки иконку передавать как пропс. Название компонента как бы говорит, что это довольно универсальный класс и мы может передать любую иконку

2023-08-27 10:37 UTC, Grinv commented on app/components/Card/Card.tsx
> +                    <p className={cn(styles.dot)}>·</p>
Лучше такие буллеты добавлять через псевдоэлементы
https://css-tricks.com/everything-you-need-to-know-about-the-gap-after-the-list-marker/

2023-08-27 10:37 UTC, Grinv commented on app/components/Card/Card.tsx
> +                <img src={imageLink} alt={'media'}/>
Давай тут использовать компонент `next/image`

2023-08-27 10:37 UTC, Grinv commented on app/components/Card/Card.tsx
> +        <div className={cn(styles.card)}>
Карточки лучше оборачивать в тэг article
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article
>Examples include: a forum post, a magazine or newspaper article, or a blog entry, a product card, a user-submitted comment, an interactive widget or gadget, or any other independent item of content.

2023-08-27 10:37 UTC, Grinv commented on app/components/Card/Card.tsx
> +                <img src={imageLink} alt={'media'}/>
А зачем тут обёртка для картинки? Можно добавить класс и к картинке

2023-08-27 10:37 UTC, Grinv commented on app/components/Card/Card.tsx
> +                    <p className={cn(styles.text)}>{tag}</p>
В тэг p мы оборачиваем абзац, либо законченное предложение.
Фразы, состоящие из одного-двух слов в p не надо обрамлять

2023-08-27 10:37 UTC, Grinv commented on app/components/Read/Read.tsx
> +        <div className={styles.read}>
Это ссылка или кнопка?
Если ссылка - то в компонент `next/link`
Если кнопка - то в тэг button

2023-08-27 10:37 UTC, Grinv commented on app/components/Read/Read.tsx
> +import ReadArrow from '../../../public/arrow.svg';
Лучше положить иконки в `/public/icons`, чтоб в public был порядок

2023-08-27 10:37 UTC, Grinv commented on app/components/Read/Read.tsx
> +import ReadArrow from '../../../public/arrow.svg';
Давай и для public сделаем alias, чтоб мы могли обращаться через `@/public/icons`

2023-08-27 10:37 UTC, Grinv commented on app/components/Card/Card.tsx
> +                <Read text={'Читать'}/>
Это ж интерактивный элемент, надо будет внутрь передать какой-то id

2023-08-27 10:37 UTC, Grinv commented on app/components/Card/Card.tsx
> +            <div className={cn(styles.bottom)}>
Можно использовать тэг footer

2023-08-27 10:37 UTC, Grinv commented on app/components/Likes/Likes.module.css
> +	margin-top: -1px;
Зачем отрицательный margin?

2023-08-27 10:37 UTC, Grinv commented on app/components/Likes/Likes.tsx
> +        <div className={cn(styles.likes)}>
Зачем тут label?
Впринципе, это всё будет кликабельная область, если мы хотим дать пользователю возможность ставить like.
Поэтому весь этот компонент должен быть обёрнут в button

2023-08-27 10:37 UTC, Grinv commented on app/components/P/P.tsx
> +        <p className={cn(stypes.p,className, {[stypes.small]: size === 's', [stypes.medium]: size === 'm', [stypes.large]: size === 'l'})} {...props}>{children}</p>
```jsx
const classes = cn(stypes.p, className, {
  [stypes.small]: size === 's',
  [stypes.medium]: size === 'm',
  [stypes.large]: size === 'l',
});

return (
  <p {...props} className={classes}>
    {children}
  </p>
);

2023-08-27 10:37 UTC, Grinv commented on app/components/Tag/Tag.tsx
> +                href ? <a href={href}>{children}</a> : <>{children}</>
Если ссылка, то нам не нужна обёртка из div. Пусть основная обёртка и будет ссылкой.

Лучше стараться делать использовать минимальное количество вложенностей и элементов. Это в том числе и на оптимизации сказывается

2023-08-27 10:37 UTC, Grinv commented on app/layout.tsx
> +  variable: '--noto-sans-font',
А зачем variable, если мы его нигде не используем?)

2023-08-27 10:37 UTC, Grinv commented on app/layout.tsx
> +  fallback: ['sans-serif'],
Можно не указывать, там и так есть фоллэчный шрифт по-умолчанию

2023-08-27 10:37 UTC, Grinv commented on app/layout.tsx
> +  weight: ['300', '400', '500', '700'],
font-weight: 300 мы не используем, поэтому лучше убрать, чтоб облегчить размер шрифта

2023-08-27 10:37 UTC, Grinv commented on app/layout.tsx
> +      <body className={notoSans.className}>{children}</body>
Лучше всё-таки делать так:
Мы задаём в шрифте 
```
variable: '--noto-sans-font',
```
В body прописываем:
```
className={notoSans.variable}
```
и далее в globals.css указываем
```css
body {
   font-family: var(--noto-sans-font);
}

2023-08-27 10:37 UTC, Grinv commented on app/page.tsx
> +        <Button appear={'primary'} direction={'down'}>Читать отзывы</Button>
Зачем тут везде вокруг пропсов, которые строки, оборачивать в фигурные скобки?)
```jsx
<Button appear="primary" direction="down">Читать отзывы</Button>

2023-08-27 10:37 UTC, Grinv commented on package.json
> +    "@svgr/webpack": "^8.1.0",
Всё-что не работает на продакшене. А всё, что нужно для проверки, сборки, транспайлеры - в devDependencies

2023-08-31 17:46 UTC, Grinv commented
![Screenshot 2023-09-01 at 01 45 31](https://github.com/EgorLepskii/react-project/assets/4070730/1d357820-fc56-4b94-b8cf-e051c44501b0)
Не все комментарии поправил, вот тут нажми на кнопку "Load more" :)

2023-09-01 03:37 UTC, EgorLepskii commented on app/components/Card/Card.tsx
> +                    <p className={cn(styles.text)}>{tag}</p>
А какой тег лучше всего использовать для этой цели? Мне нужно в любом случае задать стили этому тексту, поэтому нужен какой то тег

2023-09-01 03:44 UTC, EgorLepskii commented on app/components/Read/Read.tsx
> +        <div className={styles.read}>
По логике это конечно ссылка, обернул в next/link

2023-09-01 04:12 UTC, EgorLepskii commented on app/components/Read/Read.tsx
> +import ReadArrow from '../../../public/arrow.svg';
Добавил alias

2023-09-01 04:15 UTC, EgorLepskii commented on app/components/Likes/Likes.module.css
> +	margin-top: -1px;
Он тут лишний, мне тогда казалось, что иконка неровно расположена относительно макета, поэтому добавил. Но сейчас посмотрел, что от этого только хуже, убрал

2023-09-01 10:45 UTC, EgorLepskii commented on app/components/Likes/Likes.tsx
> +        <div className={cn(styles.likes)}>
Мне нужно было добавить отступ для текста, соответственно для этого нужен тег, на который мы повесим стили. Если я правильно понял, теги p и label тут неуместны и более уместным является span

2023-09-01 11:27 UTC, EgorLepskii commented on app/layout.tsx
> +  variable: '--noto-sans-font',
не понял вопрос, я же использую его в globals.css в теге body
`body {
	overflow-x: hidden;

	max-width: 100vw;

	color: var(--black);
	background: #F5F6F8;

	font-family: var(--noto-sans-font);
}`

2023-09-01 11:38 UTC, EgorLepskii commented on app/components/Card/Card.tsx
> +                <Read text={'Читать'}/>
Извиняюсь, куда передавать? Имелось ввиду возможность присвоить для компоненты id?

2023-09-03 09:34 UTC, EgorLepskii commented on app/components/Card/Card.tsx
> +                    <p className={cn(styles.text)}>{tag}</p>
Сейчас добавил span

2023-09-03 10:00 UTC, Grinv commented on app/components/Card/Card.tsx
> +                    <p className={cn(styles.text)}>{tag}</p>
Логика такая - ищем подходящий тэг по смыслу. Если нет - оборачиваем в div или span.
Для бейджей семантически верных тэгов нет, поэтому используем или span или div. Зависит от того, как отвёрстано.

2023-09-03 10:03 UTC, Grinv commented on app/components/Card/Card.tsx
> +                <Read text={'Читать'}/>
Ну если это ссылка, то она будет доступна по какому-то урлу? Правильно? Как обычно мы генерим урл поста? Либо по id, либо по slug
`/post/123`
`/post/2211`
Тебе необходимо передать id, чтоб внутри компонента Read сформировать ссылку на этот пост)
```jsx
`/posts/${props.postId}`

2023-09-03 10:06 UTC, Grinv commented on app/components/Likes/Likes.tsx
> +        <div className={cn(styles.likes)}>
Конечно. Про кнопки описал тут в комментариях: https://github.com/EgorLepskii/react-project/pull/2#discussion_r1314188951

Ты можешь вешать стили на button, почему нет?
<button className={cn(styles.likes)}>content</button>

2023-09-03 10:10 UTC, Grinv commented on app/layout.tsx
> +  variable: '--noto-sans-font',
Хм. Либо я пропустил это. Либо поправил код. Если пропустил - извиняюсь. Сейчас всё корректно

2023-09-08 06:03 UTC, Grinv commented on .idea/.gitignore
Файл всеравно остался)
Я обычно делаю так. Удаляю его - делают коммит - прописываю в gitignore - потом снова возращаю в проект и гит его уже не видит и как будто не было)

2023-09-08 06:03 UTC, Grinv commented on app/components/Button/Button.module.css
> +	width: 148px;
Всё-таки я рекомендую не выставлять так жёстко размеры кнопок. Может текст поменяться или переводы добавиться или иконка другого размера добавится) Кнопка должна именно под размер внутреннего контента подстраиваться)

2023-09-08 06:03 UTC, Grinv commented on app/components/Button/Button.module.css
> +	margin-left: 11px;
У тебя же кнопка display: flex. Удобнее отступы делать не через margin, а через gap
```css
.button {
   gap: 11px;
}

2023-09-08 06:03 UTC, Grinv commented on app/components/Button/Button.module.css
> +	transition: all 0.2s;
А transition тут зачем? Вроде тут не должно быть анимации. Просто transform без transition надо

2023-09-08 06:03 UTC, Grinv commented on app/components/Button/Button.tsx
> +    const labelClasses = cn(styles.arrow, {
Ты же не знаешь, что за иконка сюда придёт :) Может это вообще не стрелка будет. Тебе надо иконку сюда уже со стилями передавать, если они вообще нужны.
Я бы указал какие-то общие стили. Например
```
width: ...;
height: ...;

.button:hover svg path {
   fill: currentColor;
}
```
Это обусловлено дизайн-системой, чтоб иконки всегда были одного размера.
Другие частные стили задаём иконке. когда передаём её.
Ну или опять же, можно в кнопку передать класс, в котором мы эти частные стили опишем

2023-09-08 06:03 UTC, Grinv commented on app/components/Card/Card.module.css
> +	background: #E5F4FF;
А чего все эти стили не в css переменных?)

2023-09-08 06:03 UTC, Grinv commented on app/components/Card/Card.module.css
> +.time::marker {
👍

2023-09-08 06:03 UTC, Grinv commented on app/components/Card/Card.module.css
> +	-webkit-line-clamp: 4;
Осторожно с этим свойством. Оно достаточно поломано в Safari. Лучше там тоже проверить, если есть возможность

2023-09-08 06:03 UTC, Grinv commented on app/components/Card/Card.tsx
> +                layout='responsive'
свойства layout больше не существует в 13 версии некста)
Тебе надо `fill` передавать
Если ты хочешь, чтоб картинка тянулась по размерам, тебе надо применить fill и object-fit
https://nextjs.org/docs/pages/api-reference/components/image#responsive-image-with-fill

2023-09-08 06:03 UTC, Grinv commented on app/components/Read/Read.tsx
> +            <div className={styles.read}>
А зачем тут div?
Почему бы не сделать вот так
```jsx
<Link href={`https://jsonplaceholder.typicode.com/posts/${id}`} className={styles.read}>

2023-09-08 06:03 UTC, Grinv commented on app/layout.tsx
> +  variable: '--noto-sans-font'
👍

2023-09-08 06:03 UTC, Grinv commented on app/layout.tsx
> +  title: 'My Blog'
Ну раз у тебя в `html` прописано `lang=ru` и контент на русском, сделай пожалуйста тогда и title на русском)

2023-09-08 06:03 UTC, Grinv approved these changes

2023-09-08 06:03 UTC, merged

2023-09-08 11:35 UTC, EgorLepskii commented on app/components/Button/Button.module.css
> +	width: 148px;
добавил min-width

2023-09-08 13:40 UTC, EgorLepskii commented on app/components/Read/Read.tsx
> +            <div className={styles.read}>
Поправил

2023-09-09 06:15 UTC, EgorLepskii commented on app/components/Button/Button.tsx
> +    const labelClasses = cn(styles.arrow, {
Подскажи, я тут проблему обнаружил. У меня, если я пытаюсь в кнопке организовать вставку текста и иконки, получаются какие-то сложные конструкции. Вот  если передавать текст и к нему внутри кнопки подставлять еще и иконку,для которой я добавляю margin-left, то при добавлении этого отступа текст кнопки перемещается вправо, а должен быть по середине. Я думал, сделать возможность тому, кто использует этот компонент, передавать текст и иконку как children внутрь кнопки и тем самым пользователь сможет задать отступы для текста и иконки самостоятельно, но я не уверен, что так правильно.

2023-09-09 07:53 UTC, EgorLepskii commented on app/components/Card/Card.tsx
> +                layout='responsive'
Изображению при использовании этих свойств выставляется абсолютное позиционирование. И оно перекрывает контент снизу. Для решения проблемы нужно будет опять обернуть его в div

2023-09-14 14:16 UTC, Grinv commented on app/components/Button/Button.tsx
> +    const labelClasses = cn(styles.arrow, {
Задавай стили внутри кнопки при помощи
```css
display: flex;
gap: 18px;
```
Если в кнопке несколько элементов - отступ применится. Если нет, то не будет отступа

2023-09-14 14:17 UTC, Grinv commented on app/components/Card/Card.tsx
> +                layout='responsive'
Ну да, как и написано в статье. Я ж для этого и приложил ссылку

2023-09-15 12:34 UTC, EgorLepskii commented on app/components/Button/Button.tsx
> +    const labelClasses = cn(styles.arrow, {
Я кажется идею не понял, тут gap не будет работать. У меня иконка должна быть в правой части, а текст по середине. Если использовать gap, то текст не останется по середине, а уйдет в левую часть. Я сейчас добавил flex:1, это позволило сместить иконку в правую часть, а текст оставить по середине. Также добавил возможность стили для иконки настраивать  извне

2023-09-15 12:38 UTC, EgorLepskii commented on app/components/Card/Card.tsx
> +                layout='responsive'
Ну просто до этого была правка о том, что желательно в этом месте не добавлять div, а вешать стили прямо на изображение) Я исправил, а сейчас пришлось вернуть)

2023-09-15 12:41 UTC, EgorLepskii commented on app/components/Button/Button.module.css
> +	margin-left: 11px;
У меня сейчас отступ от правой части кнопки, я добавил margin-right, gap сейчас не подойдет

2023-09-15 13:02 UTC, EgorLepskii commented on app/components/Card/Card.module.css
> +	-webkit-line-clamp: 4;
запустил на browserstack, вроде работает