2 components
EgorLepskii/react-project pull request #2
Opened 2023-09-02 05:23 UTC by EgorLepskii

2023-09-03 09:15 UTC, Grinv requested changes

2023-09-03 09:15 UTC, Grinv commented on .idea/jsLibraryMappings.xml
В `.gitignore`
Настройки `.vscode`, `.idea` - это личные настройки каждого, в репозитории их быть не должно

2023-09-03 09:15 UTC, Grinv commented on .idea/vcs.xml
Тоже самое, в gitignore

2023-09-03 09:15 UTC, Grinv commented on app/(auth)/layout.tsx
> +        <div style={{border: "1px solid red"}}>
Не надо так) Нужно убрать в css

2023-09-03 09:15 UTC, Grinv commented on app/(auth)/layout.tsx
> +                                       children,
Что тут с отступами?)

2023-09-03 09:15 UTC, Grinv commented on app/(auth)/layout.tsx
> +    children: React.ReactNode
Лучше типы выносить и не мешать с пропсами. Там проще и удобнее читать код
```jsx
interface Props {
   children: React.ReactNode
}

export default function AuthLayout({ children }: Props) {

2023-09-03 09:15 UTC, Grinv commented on app/(auth)/login/page.tsx
> +import React from 'react';
С react 17+ не надо импорить глобальный объект `React`. Убери пожалуйста из всех файлов

2023-09-03 09:15 UTC, Grinv commented on app/(site)/blog/page.tsx
> +            <Card header='Как работать с CSS Grid'
Давай может этот как-то оформим грамотно и красиво)
Например, можно все эти данные разместить в `mockData.json`, импорировать тут и через цикл вывести
```jsx
{posts.map(post => <Card key={post.id} header={post.title} ... />)}

2023-09-03 09:15 UTC, Grinv commented on app/(site)/layout.tsx
> +                                        children,
И тут что с отступами?)

2023-09-03 09:15 UTC, Grinv commented on app/layout.tsx
> +        <body className={notoSans.className}>
Css переменная шрифта же так не работает. Тут надо передавать `notoSans.variable`, а не `notoSans.className`

2023-09-03 09:15 UTC, Grinv commented on app/layout.tsx
> +    fallback: ['sans-serif'],
Можно fallback не указывать, он там автоматически правильный подставляется

2023-09-03 09:15 UTC, Grinv commented on app/globals.css
>  }
Советую все нормалайзеры и резетеры стилей выносить в файл `preflight.css` и уже его импортировать. Так будет более чистая и понятная структура

2023-09-03 09:15 UTC, Grinv commented on app/layout.tsx
> +        <Footer/>
Отступы

2023-09-03 09:15 UTC, Grinv commented on app/page.tsx
> +            <Like handleLikeChange={() => sendRequest()}/>
Кажется компоненту Home не надо знать о том, что происходит по клику на Like.
Поэтому handleLikeChange можно инкапсулировать внутри компонента Like, убрать отсюда sendRequest и сделать компонент Home `use server`, а не `use client`
Лучше стараться делать использовать все прелести Next.js, RSC и стараться делать максимальное количество серверных компонентов, чтоб не раздувать размер бандла js

2023-09-03 09:15 UTC, Grinv commented on components/Button/Button.module.css
> +	border: 1px solid #EBEBEB;
В css переменные

2023-09-03 09:15 UTC, Grinv commented on components/Card/Card.module.css
> +.dot {
Элемент убрал, а кто будет стили убирать?) Старайся пожалуйста всегда проверять, что используется, а что нет, когда удаляешь компоненты или классы. Это постоянная проблема в рабочей практике. Когда начинаешь редизайнить или рефакторить какой-то компонент и понимаешь, что кто-то поленилсчя и оставил много неиспользуемых css правил, которые висят мёртвым грузом, затрудняют чтение и раздувают размер файла стилей

2023-09-03 09:15 UTC, Grinv commented on components/Card/Card.tsx
> +                alt={'media'}
Зачем фигурные скобки?)
```jsx
alt="media"

2023-09-03 09:15 UTC, Grinv commented on components/Card/Card.tsx
> +                        <li>{timeToRead}</li>
Почему li? Это же не список, а просто текст.

2023-09-03 09:15 UTC, Grinv commented on components/Footer/Footer.tsx
> +            <a href='#' className='e2'>Пользовательское соглашение</a>
Используем компонент `next/link`

2023-09-03 09:15 UTC, Grinv commented on components/Header/Header.tsx
> +            <p>.my_blog</p>
Ну это не параграф, тут p не нужен) 
p используем для законченных полноценных предложений

2023-09-03 09:15 UTC, Grinv commented on components/Like/Like.tsx
> +        <div className={cn(styles.like, {[styles.active]: active, [styles.notActive]: !active})}
Используем onClick с кнопками. Можно вешать на div, если это обёртка над списком кнопок и мы делегируем событие. Вешать onClick на button, а не div имеет массу плюсов
1) Это семантически правильно
2) Из коробки у нас работает disable
3) Нативно работают tab, space и enter

Держи видео для затравочки)
https://youtu.be/CZGqnp06DnI?si=WQZt3EET0hCBOpUj
https://youtu.be/YAqRQoN8ykI?si=Ork6Mi6FC-vwE-q2

2023-09-03 09:15 UTC, Grinv commented on components/Likes/Likes.module.css
> +	color: #6E6E6E;
В css переменную

2023-09-03 09:15 UTC, Grinv commented on components/Likes/Likes.tsx
> +        <button className={cn(styles.btn)}>
А вот тут наоборот, зачем button?) оно же не кликабельно)
Советую при помощи tab пройтись по странице и выяснить, насколько вообще корректно настроены интерактивные кликабельные элементы

2023-09-03 09:15 UTC, Grinv commented on components/P/P.module.css
> +	color: #3B434E;
В переменную

2023-09-03 09:15 UTC, Grinv commented on components/Rating/Rating.tsx
> +import StarIcon from '../../public/star.svg';
'@/public/star.svg'

2023-09-03 09:15 UTC, Grinv commented on components/Rating/Rating.tsx
> +    const onKeyDown = (i: number, e: KeyboardEvent) => {
Делаешь из звёздочек нативные кнопки, и у тебя вообще всё из коробки начинает работать!)
И tabIndex и space и onClick. Ты можешь управлять этим состоянием просто меняя флаг `disabled`

2023-09-03 09:15 UTC, Grinv commented on components/Tag/Tag.tsx
> +        <a
используем `next/link`

2023-09-03 09:15 UTC, Grinv commented on components/Read/Read.tsx
> +            <div className={styles.read}>
Зачем тут div? Стараемся делать меньше вложенностей
```jsx
<Link href={link} className={styles.read}>
   <p>{text}</p>
   <ReadArrow/>
</Link>

2023-09-03 09:15 UTC, Grinv commented on package.json
>      "@types/react-dom": "18.2.7",
Все типы выносим devDependencies, мы их на продакшене не используем и они нам нужны только для разработки

2023-09-08 11:52 UTC, EgorLepskii commented on app/(auth)/layout.tsx
> +                                       children,
Странно, что автоматическое исправление в IDE с этим ничего не сделало

2023-09-08 12:33 UTC, EgorLepskii commented on app/(site)/blog/page.tsx
> +            <Card header='Как работать с CSS Grid'
Такой вопрос, а как в такой в такой ситуации отображать ссылку внутри текста? Если я правильно понял, по заданию ссылка может быть в любом месте текста. Если делать это прямо из компоненты, то можно передать текст и ссылку в пропсах как компоненты и проблем нет. Но в json я смогу задать только текст. Запихать тег в текст можно, но реакт не обработает это при выводе, а убирать экранирование не очень безопасно. Как поступить в данной ситуации?

2023-09-08 12:33 UTC, EgorLepskii commented on app/(site)/layout.tsx
> +                                        children,
Исправил

2023-09-08 12:38 UTC, EgorLepskii commented on app/layout.tsx
> +        <body className={notoSans.className}>
Я это исправил в 1-start, но не вмержил в 2-components. Сейчас все вмержил

2023-09-08 12:41 UTC, EgorLepskii commented on app/layout.tsx
> +        <Footer/>
странно, что при форматировании в IDE отступы убираются. Поправил

2023-09-08 12:53 UTC, EgorLepskii commented on app/page.tsx
> +            <Like handleLikeChange={() => sendRequest()}/>
ok

2023-09-08 12:56 UTC, EgorLepskii commented on components/Button/Button.module.css
> +	border: 1px solid #EBEBEB;
Я не очень понимаю, какой смысл. Этот цвет же только в этом файле используется, зачем выносить?

2023-09-08 13:03 UTC, EgorLepskii commented on components/Card/Card.module.css
> +.dot {
Сейчас вроде везде убрал неиспользуемые стили

2023-09-08 13:06 UTC, EgorLepskii commented on components/Card/Card.tsx
> +                        <li>{timeToRead}</li>
Было исправилено в 1-start

2023-09-08 13:08 UTC, EgorLepskii commented on components/Footer/Footer.tsx
> +            <a href='#' className='e2'>Пользовательское соглашение</a>
Тут подразумевается, что это ссылки внутри сайта?  Если я правильно понял, то next/link только для подобного рода ссылок создан.

2023-09-08 13:17 UTC, EgorLepskii commented on components/Header/Header.tsx
> +            <p>.my_blog</p>
Делал задания в этой ветке до того, как просмотрел ревью 1-start, поэтому тут могут быть повторения ошибок. Сейчас все смержил, вроде все поправил

2023-09-08 13:19 UTC, EgorLepskii commented on components/Likes/Likes.module.css
> +	color: #6E6E6E;
Опять, это же единичный случай такой переменной

2023-09-08 13:25 UTC, EgorLepskii commented on components/Read/Read.tsx
> +            <div className={styles.read}>
непривычно просто на ссылки ставить стили по типу display: flex. Поправил

2023-09-08 13:26 UTC, EgorLepskii commented on package.json
>      "@types/react-dom": "18.2.7",
вынес

2023-09-09 03:11 UTC, EgorLepskii commented on components/Like/Like.tsx
> +        <div className={cn(styles.like, {[styles.active]: active, [styles.notActive]: !active})}
Добавил button

2023-09-09 03:15 UTC, EgorLepskii commented on components/Likes/Likes.tsx
> +        <button className={cn(styles.btn)}>
https://github.com/EgorLepskii/react-project/pull/1#discussion_r1306639144 - вот тут написали, что вся компонента должна быть обернута в button, тк это все кликабельная область

2023-09-09 03:59 UTC, EgorLepskii commented on components/Rating/Rating.tsx
> +    const onKeyDown = (i: number, e: KeyboardEvent) => {
Да, это действительно удобно. Только onMouseLeave продолжает работать при disabled. Поправил

2023-09-09 04:07 UTC, EgorLepskii commented on components/Button/Button.module.css
> +	border: 1px solid #EBEBEB;
Тут к также куча оттенков белого цвета, которые на глаз практически не отличить. Как их тогда правильно именовать?

2023-09-14 14:24 UTC, Grinv commented on app/(site)/blog/page.tsx
> +            <Card header='Как работать с CSS Grid'
Смотря откуда берётся контент постов.
Если ты их пишешь сам или специальный контент менеджер, то экранирование можно отключать. Если нет - можно воспрользоваться например библиотечкой DOMPurify (https://github.com/cure53/DOMPurify) и вставлять через dangerouslySetInnerHTML

2023-09-14 14:27 UTC, Grinv commented on components/Button/Button.module.css
> +	border: 1px solid #EBEBEB;
Окей. Сколько минимально нужно использовать цвет, чтоб добавить его в переменную? Есть стандарт?
По мне, если решил использовать css переменные, то пусть все цвета хранятся в одном месте. Сделать palette.css и сложить всё туда.

Оттенки серого)
Оттенки называют обычно так:
```css
--grey-100: #000;
--grey-200: #000;
--grey-300: #000;
--grey-400: #000;
```
Для примера можешь глянуть, как делает tailwind (https://tailwindcss.com/docs/customizing-colors)

2023-09-14 14:35 UTC, Grinv commented on components/Likes/Likes.tsx
> +        <button className={cn(styles.btn)}>
А зачем делаешь тогда компонент <Like /> ещё кликабельным?
Кликабельный элемент внутри кликабельного элемента?)

Likes - это вообще странное название, которое сбивает с толку. Назывется Likes, кажется, что там список лайков, а это просто кнопка со счётчиком.
Лучше удалить Likes, сделать одну большую кнопку Like и всё переместить в неё.
Будет типа того
```jsx
<button onClick={onClick}>
   {likesAmount}
   <Image href={likeIconUrl} />
</button>
```
Вот для примера facebook. Там и счётчик и иконка в одной кнопке)
![image](https://github.com/EgorLepskii/react-project/assets/4070730/5986a6f9-05fb-40a2-8e23-fc4731b96d6f)

2023-09-15 13:28 UTC, EgorLepskii commented on app/(site)/blog/page.tsx
> +            <Card header='Как работать с CSS Grid'
ок, добавил DOMpurify с доступным тегом a

2023-09-15 14:19 UTC, EgorLepskii commented on components/Likes/Likes.tsx
> +        <button className={cn(styles.btn)}>
Название действительно странное, поправил. 
А зачем делаешь тогда компонент ещё кликабельным?
Вот этот вопрос, к сожалению, не понял, у меня весь компонент - это иконка лайка и количество лайков, и все это обернуть в button, т.е кликабельно

2023-09-24 06:38 UTC, Grinv approved these changes

2023-09-24 06:38 UTC, Grinv commented on app/(site)/about/page.tsx
> +    const iconStyles = cn(styles.svg, styles.svg);
Дублирование стилей

2023-09-24 06:38 UTC, Grinv commented on app/(site)/blog/page.tsx
> +                return <Card header={post.header}
Забыл добавить key

2023-09-24 06:38 UTC, Grinv commented on components/Like/LikeButton.tsx
> +        <button className={cn(styles.like, {[styles.active]: active, [styles.notActive]: !active})}
Не очень понял, зачем делать not_active_button и active_button.
Можно впринципе приравнять not_active_button к обычному состоянию кнопки) Так оно по логике и выходит.
```jsx
<button className={cn(styles.like, {[styles.active]: active)}

2023-09-24 06:38 UTC, Grinv commented on components/Rating/Rating.tsx
> +                        constructRating(index + 1);
Вообще кстати можно было бы поиграться с has и попробовать сделать без onMouseEnter и onMouseLeave
https://tobiasahlin.com/blog/previous-sibling-css-has

Вот тут ребята ещё обсуждали. Можно поизучать и попробовать)
https://stackoverflow.com/questions/1817792/is-there-a-previous-sibling-selector

2023-09-24 06:38 UTC, Grinv commented on package.json
>      "eslint-config-next": "13.4.16",
в devDependencies

2023-09-24 06:38 UTC, Grinv commented on package.json
>      "typescript": "5.1.6"
в в devDependencies

2023-09-24 06:38 UTC, merged